# Auto-generated by /home/arun/Desktop/darpa_ex1/edk2-vulnerable/BaseTools/BuildEnv
if [ -z "$WORKSPACE" ]
then
  export WORKSPACE=/home/arun/Desktop/darpa_ex1/edk2-darpa
fi
if [ -z "$EDK_TOOLS_PATH" ]
then
  export EDK_TOOLS_PATH=/home/arun/Desktop/darpa_ex1/edk2-vulnerable/BaseTools
fi
if [ -e /home/arun/Desktop/darpa_ex1/edk2-vulnerable/BaseTools/Bin/Linux-x86_64 ]
then
  if [ ${PATH//home/arun/Desktop/darpa_ex1/edk2-vulnerable/BaseTools/Bin/Linux-x86_64/} == $PATH ]
  then
    export PATH=/home/arun/Desktop/darpa_ex1/edk2-vulnerable/BaseTools/Bin/Linux-x86_64:$PATH
  fi
fi
